workflows:
  android-build:
    name: Android APK Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      node: 20
      java: 17
      
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
          
      - name: Expo prebuild
        script: |
          npx expo prebuild --platform android --clean
          
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
          
      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease
          
    artifacts:
      - android/app/build/outputs/**/*.apk
      
    publishing:
      email:
        recipients:
          - rohanigamerrg@gmail.com
        notify:
          success: true
          failure: true
